//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

    using System;
    using System.Collections.Generic;
using System.Runtime.Serialization;

namespace PilMoney.Models
{
    [DataContract]
    public class Compras
    {
       [DataMember]
       private int idCompra;
        [DataMember]
        private double importe;
        [DataMember]
        private System.DateTime fecha;
        [DataMember]
        private string cvu;
      

       public Compras(int idCompra, double importe, System.DateTime fecha, string cvu){

           this.idCompra = idCompra;
           this.importe = importe;
           this.fecha = fecha;
           this.cvu = cvu;
        
       }

       public int IdCompra {get => idCompra; set => idCompra = value;}
       public double Importe {get => importe; set => importe = value;}
       public System.DateTime Fecha {get => fecha; set => fecha = value;}
       public string CVU {get => cvu; set => cvu = value;}
       
    }
}
