//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

    using System;
    using System.Collections.Generic;

namespace PilMoney.Models
{
    
    public class Compras
    {
       private int idCompra;
       private float importe;
       private System.DateTime fecha;
       private string cvu;
      

       public Compras(int idCompra, float importe, System.DateTime fecha, string cvu){

           this.idCompra = idCompra;
           this.importe = importe;
           this.fecha = fecha;
           this.cvu = cvu;
        
       }

       public int IdCompra {get => idCompra; set => idCompra = value;}
       public float Importe {get => importe; set => importe = value;}
       public System.DateTime Fecha {get => fecha; set => fecha = value;}
       public string CVU {get => cvu; set => cvu = value;}
       
    }
}
