//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

 using System;
 using System.Collections.Generic;

namespace PilMoney.Models
{
   
    public class Contactos
    {
        private int idContacto;
        private string cvu;
        private string aliasContacto;
        private string cvuContacto;
        private Cuentas cuentas;

        public Contactos(int idContacto, string cvu; string aliasContacto, string cvuContacto, Cuentas cuentas){
            this.idContacto = idContacto;
            this.cvu = cvu;
            this.aliasContacto = aliasContacto;
            this.cvuContacto = cvuContacto;
            this.cuentas = cuentas;
        }
        public int IdContacto {get => idContacto; set => idContacto = value;}
        public string CVU {get => cvu; set => cvu = value;}
        public string AliasContacto {get => aliasContacto; set => aliasContacto = value;}
        public string CVUContacto {get => cvuContacto; set => cvuContacto = value;}
    }
}
