//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

 using System;
 using System.Collections.Generic;

namespace PilMoney.Models
{
    
    public class Depositos
    {
        private int idDeposito;
        private double importe;
        private string cvu;
        private string alias;
       

        public Depositos(int idDeposito, double importe, string cvu, string alias){
            this.idDeposito = idDeposito;
            this.importe = importe;
            this.cvu = cvu;
            this.alias = alias;
           
        }

        public int IdDeposito {get => idDeposito; set => idDeposito = value;}
        public double Importe {get => importe; set => importe = value;}
        public string CVU {get => cvu; set => cvu = value;}
        public string Alias {get => alias; set => alias = value;}
    }
}
