//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

 using System;
 using System.Collections.Generic;

namespace PilMoney.Models
{
    
    public class Depositos
    {
        private int idDeposito;
        private float importe;
        private string cvu;
        private string alias;
        private Cuentas cuentas;

        public Depositos(int idDeposito, float importe, string cvu, string alias, Cuentas cuentas){
            this.idDeposito = idDeposito;
            this.importe = importe;
            this.cvu = cvu;
            this.alias = alias;
            this.cuentas = cuentas;
        }

        public int IdDeposito {get => idDeposito; set => idDeposito = valeu;}
        public float Importe {get => importe; set => importe = value;}
        public string CVU {get => cvu; set => cvu = value;}
        public Cuentas Cuentas {get => cuentas; set => cuentas = value;}
    }
}
