//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

 using System;
 using System.Collections.Generic;

namespace PilMoney.Models
{
    
    public class Inversiones
    {
          private int idInversion;
          private string tipoInversion;
          private double importe;
          private System.DateTime fecha;
          private byte renovacion;
          private string cvu;
     

          public Inversiones(int idInversion, string tipoInversion, double importe, System.DateTime fecha, byte renovacion, string cvu){

              this.idInversion = idInversion;
              this.tipoInversion = tipoInversion;
              this.importe = importe;
              this.fecha = fecha;
              this.renovacion = renovacion;
              this.cvu = cvu;
              
          }

          public int IdInversion {get => idInversion; set => idInversion = value;}
          public string TipoInversion {get => tipoInversion; set => tipoInversion = value;}
          public double Importe {get => importe; set => importe = value;}
          public System.DateTime Fecha {get => fecha; set => fecha = value;}
          public byte Renovacion {get => renovacion; set => renovacion = value;}
          public string CVU {get => cvu; set => cvu = value;}
         

    }
}
 