//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

 using System;
 using System.Collections.Generic;

namespace PilMoney.Models
{
   
    public class TipoMonedas
    {
        private int idTipoMoneda;
        private string nombre;
        private Cuentas cuentas;

        public TipoMonedas(int idTipoMoneda, string nombre, Cuentas cuentas){
            this.idTipoMoneda = idTipoMoneda;
            this.nombre = nombre;
            this.cuentas = cuentas;
        }

        public int IdTipoMoneda {get => idTipoMoneda; set => idTipoMoneda = value;}
        public string Nombre {get => nombre; set => nombre = value;}
        public Cuentas Cuentas {get => cuentas; set => cuentas = value;}
    }
}
