//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

 using System;
 using System.Collections.Generic;

namespace PilMoney.Models
{
   
    public class Transferencias
    {
        private int idTransferencia;
        private System.DateTime fecha;
        private float importe;
        private int idContacto;
        private string cvu;
        private string cvuDestino;
        private string aliasDestino;
      

        public Transferencias(int idTransferencia, System.DateTime fecha, float importe, int idContacto, string cvu, string cvuDestino, string aliasDestino){
            this.idTransferencia = idTransferencia;
            this.fecha = fecha;
            this.importe = importe;
            this.idContacto = idContacto;
            this.cvu = cvu;
            this.cvuDestino = cvuDestino;
            this.aliasDestino = aliasDestino;
            
        }

        public int IdTranferencia {get => idTransferencia; set => idTransferencia = value;}
        public System.DateTime Fecha {get => fecha; set => fecha = value;}
        public float Importe {get => importe; set => fecha = value;}
        public int IdContacto {get => idContacto; set => idContacto = value;}
        public string CVU {get => cvu; set => cvu = value;}
        public string CVUDestino {get => cvuDestino; set => cvuDestino = value;}
        public string AliasDestino {get => aliasDestino; set => aliasDestino = value;}
     

}
    }

  
