//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PilMoney.Models
{
    
    public class Usuarios
    {
        private string cuil;
        private string email;
        private string contraseña;
        private string nombreCompleto;
        private System.DateTime fechaNacimiento;
        private string telefono;
        private Byte[] imagenDNI;
        private int idUsuario;
        
        

        public Usuarios(string cuil, string email, string contraseña, string nombreCompleto, System.DateTime fechaNacimiento, string telefono, Byte[] imagenDNI, int idUsuario){
            this.cuil = cuil;
            this.email = email;
            this.contraseña = contraseña;
            this.nombreCompleto = nombreCompleto;
            this.fechaNacimiento = fechaNacimiento;
            this.telefono = telefono;
            this.imagenDNI = imagenDNI;
            this.idUsuario = idUsuario;
          
        }

        public string CUIL {get => cuil; set => cuil = value;}
        public string Email {get => email; set => email = value;}
        public string Contraseña {get => contraseña; set => contraseña = value;}
        public string NombreCompleto {get => nombreCompleto; set => nombreCompleto = value;}
        public System.DateTime FechaNacimiento {get => fechaNacimiento; set => fechaNacimiento = value;}
        public string Telefono {get => telefono; set => telefono = value;}
        public Byte[] ImagenDNI {get => imagenDNI; set => imagenDNI = value;}
        public int IdUsuario { get => idUsuario; set => idUsuario = value; }
       
    }
}
